server:
  port: 9191

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        # 当线程池中的任务队列已满，并且没有空闲线程可以执行新任务时，CallerRunsPolicy 会将任务回退到调用者线程中运行。这种策略适用于不希望丢失任务且可以接受调用者线程被阻塞的场景。
        policy: CallerRunsPolicy

wrench:
  config:
    system: test-system
    register:
      # redis host
      host: 127.0.0.1
      # redis port
      port: 6379

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml